/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FfButton {
        /**
          * @default false
         */
        "disabled": boolean;
        "ffAriaLabel"?: string;
        /**
          * @default false
         */
        "fullWidth": boolean;
        "label"?: string;
        "setFocus": () => Promise<void>;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
    }
}
export interface FfButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFfButtonElement;
}
declare global {
    interface HTMLFfButtonElementEventMap {
        "ffClick": MouseEvent;
    }
    interface HTMLFfButtonElement extends Components.FfButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFfButtonElementEventMap>(type: K, listener: (this: HTMLFfButtonElement, ev: FfButtonCustomEvent<HTMLFfButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFfButtonElementEventMap>(type: K, listener: (this: HTMLFfButtonElement, ev: FfButtonCustomEvent<HTMLFfButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFfButtonElement: {
        prototype: HTMLFfButtonElement;
        new (): HTMLFfButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ff-button": HTMLFfButtonElement;
    }
}
declare namespace LocalJSX {
    interface FfButton {
        /**
          * @default false
         */
        "disabled"?: boolean;
        "ffAriaLabel"?: string;
        /**
          * @default false
         */
        "fullWidth"?: boolean;
        "label"?: string;
        "onFfClick"?: (event: FfButtonCustomEvent<MouseEvent>) => void;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'ghost' | 'danger';
    }

    interface FfButtonAttributes {
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
        "fullWidth": boolean;
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
        "label": string;
        "ffAriaLabel": string;
    }

    interface IntrinsicElements {
        "ff-button": Omit<FfButton, keyof FfButtonAttributes> & { [K in keyof FfButton & keyof FfButtonAttributes]?: FfButton[K] } & { [K in keyof FfButton & keyof FfButtonAttributes as `attr:${K}`]?: FfButtonAttributes[K] } & { [K in keyof FfButton & keyof FfButtonAttributes as `prop:${K}`]?: FfButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ff-button": LocalJSX.IntrinsicElements["ff-button"] & JSXBase.HTMLAttributes<HTMLFfButtonElement>;
        }
    }
}
