/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    /**
     * ff-button — framework-agnostic button primitive.
     * ## Architectural role
     * Owns semantic behavior and a stable DOM contract. Visual identity is supplied from
     * outside via CSS custom properties (token contract + brand pack). This file never
     * references colors, fonts, or spacing values directly.
     * ## SSR / SSG readiness contract
     * This component is written to be safe inside any server rendering context
     * (Next.js RSC, Angular Universal, Nuxt, Vite prerender, Stencil hydrate).
     *  1. The render() method is a pure function of props — no DOM access, no browser globals.
     *  2. connectedCallback has NO side effects. Any API that requires a real DOM
     *     (focus, click dispatch, observers) is only touched inside componentDidLoad,
     *     which Stencil deliberately does not invoke in the hydrate module.
     *  3. Public imperative methods (`setFocus`, `click`) are server-safe: they short-circuit
     *     when the host element is not attached to a real document.
     *  4. Shadow DOM output is serialized by the Stencil hydrate module as
     *     Declarative Shadow DOM (`<template shadowrootmode="open">`), so the first paint
     *     is correct even before client-side JS finishes downloading.
     *  5. State that differs between server and client (media queries, stored preferences)
     *     is NEVER read inside this file. The consumer passes brand/theme through the shell
     *     element's `data-brand` / `data-theme` attributes, which the CSS cascade picks up.
     * ## Where the visual identity comes from (NOT here)
     *  - ff-button.css reads --ff-button-* CSS custom properties (bg, fg, radius, padding).
     *  - Those variables are defined in packages/tokens/src/contract.css (stable API).
     *  - Concrete brand values come from packages/brand-styles/src/*.css.
     *  - The consumer app shell sets data-brand + data-theme on any ancestor → the token
     *    cascade applies the correct overrides via attribute selectors in the brand pack.
     */
    interface FfButton {
        /**
          * Disables pointer and keyboard interaction on the native button element.
          * @default false
         */
        "disabled": boolean;
        /**
          * Optional aria-label for accessible name when the button only contains an icon.
         */
        "ffAriaLabel"?: string;
        /**
          * Expands the host to full width without coupling layout rules to a brand theme.
          * @default false
         */
        "fullWidth": boolean;
        /**
          * Provides a simple fallback label when no slotted content is passed.
         */
        "label"?: string;
        /**
          * Imperatively move keyboard focus to the underlying native button. SSR-safe: the hydrate module never invokes this method because it only runs browser-triggered code paths. Still, we guard for `typeof document` to make consumer code defensively safe when called from isomorphic effects.
         */
        "setFocus": () => Promise<void>;
        /**
          * Mirrors the native button type attribute so forms keep expected behavior.
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * Semantic variant for analytics and optional brand-pack styling hooks.
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
    }
}
export interface FfButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLFfButtonElement;
}
declare global {
    interface HTMLFfButtonElementEventMap {
        "ffClick": MouseEvent;
    }
    /**
     * ff-button — framework-agnostic button primitive.
     * ## Architectural role
     * Owns semantic behavior and a stable DOM contract. Visual identity is supplied from
     * outside via CSS custom properties (token contract + brand pack). This file never
     * references colors, fonts, or spacing values directly.
     * ## SSR / SSG readiness contract
     * This component is written to be safe inside any server rendering context
     * (Next.js RSC, Angular Universal, Nuxt, Vite prerender, Stencil hydrate).
     *  1. The render() method is a pure function of props — no DOM access, no browser globals.
     *  2. connectedCallback has NO side effects. Any API that requires a real DOM
     *     (focus, click dispatch, observers) is only touched inside componentDidLoad,
     *     which Stencil deliberately does not invoke in the hydrate module.
     *  3. Public imperative methods (`setFocus`, `click`) are server-safe: they short-circuit
     *     when the host element is not attached to a real document.
     *  4. Shadow DOM output is serialized by the Stencil hydrate module as
     *     Declarative Shadow DOM (`<template shadowrootmode="open">`), so the first paint
     *     is correct even before client-side JS finishes downloading.
     *  5. State that differs between server and client (media queries, stored preferences)
     *     is NEVER read inside this file. The consumer passes brand/theme through the shell
     *     element's `data-brand` / `data-theme` attributes, which the CSS cascade picks up.
     * ## Where the visual identity comes from (NOT here)
     *  - ff-button.css reads --ff-button-* CSS custom properties (bg, fg, radius, padding).
     *  - Those variables are defined in packages/tokens/src/contract.css (stable API).
     *  - Concrete brand values come from packages/brand-styles/src/*.css.
     *  - The consumer app shell sets data-brand + data-theme on any ancestor → the token
     *    cascade applies the correct overrides via attribute selectors in the brand pack.
     */
    interface HTMLFfButtonElement extends Components.FfButton, HTMLStencilElement {
        addEventListener<K extends keyof HTMLFfButtonElementEventMap>(type: K, listener: (this: HTMLFfButtonElement, ev: FfButtonCustomEvent<HTMLFfButtonElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLFfButtonElementEventMap>(type: K, listener: (this: HTMLFfButtonElement, ev: FfButtonCustomEvent<HTMLFfButtonElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLFfButtonElement: {
        prototype: HTMLFfButtonElement;
        new (): HTMLFfButtonElement;
    };
    interface HTMLElementTagNameMap {
        "ff-button": HTMLFfButtonElement;
    }
}
declare namespace LocalJSX {
    /**
     * ff-button — framework-agnostic button primitive.
     * ## Architectural role
     * Owns semantic behavior and a stable DOM contract. Visual identity is supplied from
     * outside via CSS custom properties (token contract + brand pack). This file never
     * references colors, fonts, or spacing values directly.
     * ## SSR / SSG readiness contract
     * This component is written to be safe inside any server rendering context
     * (Next.js RSC, Angular Universal, Nuxt, Vite prerender, Stencil hydrate).
     *  1. The render() method is a pure function of props — no DOM access, no browser globals.
     *  2. connectedCallback has NO side effects. Any API that requires a real DOM
     *     (focus, click dispatch, observers) is only touched inside componentDidLoad,
     *     which Stencil deliberately does not invoke in the hydrate module.
     *  3. Public imperative methods (`setFocus`, `click`) are server-safe: they short-circuit
     *     when the host element is not attached to a real document.
     *  4. Shadow DOM output is serialized by the Stencil hydrate module as
     *     Declarative Shadow DOM (`<template shadowrootmode="open">`), so the first paint
     *     is correct even before client-side JS finishes downloading.
     *  5. State that differs between server and client (media queries, stored preferences)
     *     is NEVER read inside this file. The consumer passes brand/theme through the shell
     *     element's `data-brand` / `data-theme` attributes, which the CSS cascade picks up.
     * ## Where the visual identity comes from (NOT here)
     *  - ff-button.css reads --ff-button-* CSS custom properties (bg, fg, radius, padding).
     *  - Those variables are defined in packages/tokens/src/contract.css (stable API).
     *  - Concrete brand values come from packages/brand-styles/src/*.css.
     *  - The consumer app shell sets data-brand + data-theme on any ancestor → the token
     *    cascade applies the correct overrides via attribute selectors in the brand pack.
     */
    interface FfButton {
        /**
          * Disables pointer and keyboard interaction on the native button element.
          * @default false
         */
        "disabled"?: boolean;
        /**
          * Optional aria-label for accessible name when the button only contains an icon.
         */
        "ffAriaLabel"?: string;
        /**
          * Expands the host to full width without coupling layout rules to a brand theme.
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Provides a simple fallback label when no slotted content is passed.
         */
        "label"?: string;
        /**
          * Fired on click. Exposed as a dedicated event so consumers in every framework (React, Angular, Vue, plain HTML) can subscribe through the generated wrapper without worrying about DOM event bubbling semantics.
         */
        "onFfClick"?: (event: FfButtonCustomEvent<MouseEvent>) => void;
        /**
          * Mirrors the native button type attribute so forms keep expected behavior.
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * Semantic variant for analytics and optional brand-pack styling hooks.
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'ghost' | 'danger';
    }

    interface FfButtonAttributes {
        "disabled": boolean;
        "type": 'button' | 'submit' | 'reset';
        "fullWidth": boolean;
        "variant": 'primary' | 'secondary' | 'ghost' | 'danger';
        "label": string;
        "ffAriaLabel": string;
    }

    interface IntrinsicElements {
        "ff-button": Omit<FfButton, keyof FfButtonAttributes> & { [K in keyof FfButton & keyof FfButtonAttributes]?: FfButton[K] } & { [K in keyof FfButton & keyof FfButtonAttributes as `attr:${K}`]?: FfButtonAttributes[K] } & { [K in keyof FfButton & keyof FfButtonAttributes as `prop:${K}`]?: FfButton[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            /**
             * ff-button — framework-agnostic button primitive.
             * ## Architectural role
             * Owns semantic behavior and a stable DOM contract. Visual identity is supplied from
             * outside via CSS custom properties (token contract + brand pack). This file never
             * references colors, fonts, or spacing values directly.
             * ## SSR / SSG readiness contract
             * This component is written to be safe inside any server rendering context
             * (Next.js RSC, Angular Universal, Nuxt, Vite prerender, Stencil hydrate).
             *  1. The render() method is a pure function of props — no DOM access, no browser globals.
             *  2. connectedCallback has NO side effects. Any API that requires a real DOM
             *     (focus, click dispatch, observers) is only touched inside componentDidLoad,
             *     which Stencil deliberately does not invoke in the hydrate module.
             *  3. Public imperative methods (`setFocus`, `click`) are server-safe: they short-circuit
             *     when the host element is not attached to a real document.
             *  4. Shadow DOM output is serialized by the Stencil hydrate module as
             *     Declarative Shadow DOM (`<template shadowrootmode="open">`), so the first paint
             *     is correct even before client-side JS finishes downloading.
             *  5. State that differs between server and client (media queries, stored preferences)
             *     is NEVER read inside this file. The consumer passes brand/theme through the shell
             *     element's `data-brand` / `data-theme` attributes, which the CSS cascade picks up.
             * ## Where the visual identity comes from (NOT here)
             *  - ff-button.css reads --ff-button-* CSS custom properties (bg, fg, radius, padding).
             *  - Those variables are defined in packages/tokens/src/contract.css (stable API).
             *  - Concrete brand values come from packages/brand-styles/src/*.css.
             *  - The consumer app shell sets data-brand + data-theme on any ancestor → the token
             *    cascade applies the correct overrides via attribute selectors in the brand pack.
             */
            "ff-button": LocalJSX.IntrinsicElements["ff-button"] & JSXBase.HTMLAttributes<HTMLFfButtonElement>;
        }
    }
}
